// MIT License
//
// Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#if defined(ROCPROFILER_LIB_ROCPROFILER_VULKAN_VULKAN_CPP_IMPL) &&                                 \
    ROCPROFILER_LIB_ROCPROFILER_VULKAN_VULKAN_CPP_IMPL == 1

#    include <rocprofiler-sdk/external_correlation.h>
#    include <rocprofiler-sdk/vulkan.h>

#    include "defines.hpp"
#    include "vulkan.hpp"

namespace rocprofiler
{
namespace vulkan
{
template <>
struct vulkan_domain_info<ROCPROFILER_VULKAN_TABLE_ID_LAST>
{
    using args_type          = rocprofiler_vulkan_api_args_t;
    using retval_type        = rocprofiler_vulkan_api_retval_t;
    using callback_data_type = rocprofiler_callback_tracing_vulkan_api_data_t;
    using buffered_data_type = rocprofiler_buffer_tracing_vulkan_api_record_t;
    // using buffered_ext_data_type = rocprofiler_buffer_tracing_vulkan_api_ext_record_t;
};

template <>
struct vulkan_domain_info<ROCPROFILER_VULKAN_TABLE_ID>
: vulkan_domain_info<ROCPROFILER_VULKAN_TABLE_ID_LAST>
{
    static constexpr auto callback_domain_idx = ROCPROFILER_CALLBACK_TRACING_VULKAN_API;
    static constexpr auto buffered_domain_idx = ROCPROFILER_BUFFER_TRACING_VULKAN_API;
    // static constexpr auto buffered_ext_domain_idx = ROCPROFILER_BUFFER_TRACING_VULKAN_EXT_API;
    static constexpr auto none = ROCPROFILER_VULKAN_API_ID_NONE;
    static constexpr auto last = ROCPROFILER_VULKAN_API_ID_LAST;
    static constexpr auto external_correlation_id_domain_idx =
        ROCPROFILER_EXTERNAL_CORRELATION_REQUEST_VULKAN_API;
};

}  // namespace vulkan
}  // namespace rocprofiler

// clang-format off
VULKAN_API_TABLE_LOOKUP_DEFINITION(ROCPROFILER_VULKAN_TABLE_ID, vulkan::core_api_table_t, core)

VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetInstanceProcAddr, vkGetInstanceProcAddr, vkGetInstanceProcAddr_fn, instance, pName)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceProcAddr, vkGetDeviceProcAddr, vkGetDeviceProcAddr_fn, device, pName)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateInstance, vkCreateInstance, vkCreateInstance_fn, pCreateInfo, pAllocator, pInstance)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyInstance, vkDestroyInstance, vkDestroyInstance_fn, instance, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEnumeratePhysicalDevices, vkEnumeratePhysicalDevices, vkEnumeratePhysicalDevices_fn, instance, pPhysicalDeviceCount, pPhysicalDevices)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceFeatures, vkGetPhysicalDeviceFeatures, vkGetPhysicalDeviceFeatures_fn, physicalDevice, pFeatures)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceFormatProperties, vkGetPhysicalDeviceFormatProperties, vkGetPhysicalDeviceFormatProperties_fn, physicalDevice, format, pFormatProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceImageFormatProperties, vkGetPhysicalDeviceImageFormatProperties, vkGetPhysicalDeviceImageFormatProperties_fn, physicalDevice, format, type, tiling, usage, flags, pImageFormatProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceProperties, vkGetPhysicalDeviceProperties, vkGetPhysicalDeviceProperties_fn, physicalDevice, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceQueueFamilyProperties, vkGetPhysicalDeviceQueueFamilyProperties, vkGetPhysicalDeviceQueueFamilyProperties_fn, physicalDevice, pQueueFamilyPropertyCount, pQueueFamilyProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceMemoryProperties, vkGetPhysicalDeviceMemoryProperties, vkGetPhysicalDeviceMemoryProperties_fn, physicalDevice, pMemoryProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateDevice, vkCreateDevice, vkCreateDevice_fn, physicalDevice, pCreateInfo, pAllocator, pDevice)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyDevice, vkDestroyDevice, vkDestroyDevice_fn, device, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEnumerateInstanceExtensionProperties, vkEnumerateInstanceExtensionProperties, vkEnumerateInstanceExtensionProperties_fn, pLayerName, pPropertyCount, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEnumerateDeviceExtensionProperties, vkEnumerateDeviceExtensionProperties, vkEnumerateDeviceExtensionProperties_fn, physicalDevice, pLayerName, pPropertyCount, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEnumerateInstanceLayerProperties, vkEnumerateInstanceLayerProperties, vkEnumerateInstanceLayerProperties_fn, pPropertyCount, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEnumerateDeviceLayerProperties, vkEnumerateDeviceLayerProperties, vkEnumerateDeviceLayerProperties_fn, physicalDevice, pPropertyCount, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceQueue, vkGetDeviceQueue, vkGetDeviceQueue_fn, device, queueFamilyIndex, queueIndex, pQueue)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkQueueSubmit, vkQueueSubmit, vkQueueSubmit_fn, queue, submitCount, pSubmits, fence)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkQueueWaitIdle, vkQueueWaitIdle, vkQueueWaitIdle_fn, queue)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDeviceWaitIdle, vkDeviceWaitIdle, vkDeviceWaitIdle_fn, device)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkAllocateMemory, vkAllocateMemory, vkAllocateMemory_fn, device, pAllocateInfo, pAllocator, pMemory)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkFreeMemory, vkFreeMemory, vkFreeMemory_fn, device, memory, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkMapMemory, vkMapMemory, vkMapMemory_fn, device, memory, offset, size, flags, ppData)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkUnmapMemory, vkUnmapMemory, vkUnmapMemory_fn, device, memory)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkFlushMappedMemoryRanges, vkFlushMappedMemoryRanges, vkFlushMappedMemoryRanges_fn, device, memoryRangeCount, pMemoryRanges)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkInvalidateMappedMemoryRanges, vkInvalidateMappedMemoryRanges, vkInvalidateMappedMemoryRanges_fn, device, memoryRangeCount, pMemoryRanges)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceMemoryCommitment, vkGetDeviceMemoryCommitment, vkGetDeviceMemoryCommitment_fn, device, memory, pCommittedMemoryInBytes)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkBindBufferMemory, vkBindBufferMemory, vkBindBufferMemory_fn, device, buffer, memory, memoryOffset)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkBindImageMemory, vkBindImageMemory, vkBindImageMemory_fn, device, image, memory, memoryOffset)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetBufferMemoryRequirements, vkGetBufferMemoryRequirements, vkGetBufferMemoryRequirements_fn, device, buffer, pMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetImageMemoryRequirements, vkGetImageMemoryRequirements, vkGetImageMemoryRequirements_fn, device, image, pMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetImageSparseMemoryRequirements, vkGetImageSparseMemoryRequirements, vkGetImageSparseMemoryRequirements_fn, device, image, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceSparseImageFormatProperties, vkGetPhysicalDeviceSparseImageFormatProperties, vkGetPhysicalDeviceSparseImageFormatProperties_fn, physicalDevice, format, type, samples, usage, tiling, pPropertyCount, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkQueueBindSparse, vkQueueBindSparse, vkQueueBindSparse_fn, queue, bindInfoCount, pBindInfo, fence)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateFence, vkCreateFence, vkCreateFence_fn, device, pCreateInfo, pAllocator, pFence)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyFence, vkDestroyFence, vkDestroyFence_fn, device, fence, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkResetFences, vkResetFences, vkResetFences_fn, device, fenceCount, pFences)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetFenceStatus, vkGetFenceStatus, vkGetFenceStatus_fn, device, fence)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkWaitForFences, vkWaitForFences, vkWaitForFences_fn, device, fenceCount, pFences, waitAll, timeout)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateSemaphore, vkCreateSemaphore, vkCreateSemaphore_fn, device, pCreateInfo, pAllocator, pSemaphore)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroySemaphore, vkDestroySemaphore, vkDestroySemaphore_fn, device, semaphore, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateQueryPool, vkCreateQueryPool, vkCreateQueryPool_fn, device, pCreateInfo, pAllocator, pQueryPool)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyQueryPool, vkDestroyQueryPool, vkDestroyQueryPool_fn, device, queryPool, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetQueryPoolResults, vkGetQueryPoolResults, vkGetQueryPoolResults_fn, device, queryPool, firstQuery, queryCount, dataSize, pData, stride, flags)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateBuffer, vkCreateBuffer, vkCreateBuffer_fn, device, pCreateInfo, pAllocator, pBuffer)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyBuffer, vkDestroyBuffer, vkDestroyBuffer_fn, device, buffer, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateImage, vkCreateImage, vkCreateImage_fn, device, pCreateInfo, pAllocator, pImage)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyImage, vkDestroyImage, vkDestroyImage_fn, device, image, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetImageSubresourceLayout, vkGetImageSubresourceLayout, vkGetImageSubresourceLayout_fn, device, image, pSubresource, pLayout)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateImageView, vkCreateImageView, vkCreateImageView_fn, device, pCreateInfo, pAllocator, pView)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyImageView, vkDestroyImageView, vkDestroyImageView_fn, device, imageView, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateCommandPool, vkCreateCommandPool, vkCreateCommandPool_fn, device, pCreateInfo, pAllocator, pCommandPool)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyCommandPool, vkDestroyCommandPool, vkDestroyCommandPool_fn, device, commandPool, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkResetCommandPool, vkResetCommandPool, vkResetCommandPool_fn, device, commandPool, flags)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkAllocateCommandBuffers, vkAllocateCommandBuffers, vkAllocateCommandBuffers_fn, device, pAllocateInfo, pCommandBuffers)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkFreeCommandBuffers, vkFreeCommandBuffers, vkFreeCommandBuffers_fn, device, commandPool, commandBufferCount, pCommandBuffers)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkBeginCommandBuffer, vkBeginCommandBuffer, vkBeginCommandBuffer_fn, commandBuffer, pBeginInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEndCommandBuffer, vkEndCommandBuffer, vkEndCommandBuffer_fn, commandBuffer)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkResetCommandBuffer, vkResetCommandBuffer, vkResetCommandBuffer_fn, commandBuffer, flags)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyBuffer, vkCmdCopyBuffer, vkCmdCopyBuffer_fn, commandBuffer, srcBuffer, dstBuffer, regionCount, pRegions)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyImage, vkCmdCopyImage, vkCmdCopyImage_fn, commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyBufferToImage, vkCmdCopyBufferToImage, vkCmdCopyBufferToImage_fn, commandBuffer, srcBuffer, dstImage, dstImageLayout, regionCount, pRegions)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyImageToBuffer, vkCmdCopyImageToBuffer, vkCmdCopyImageToBuffer_fn, commandBuffer, srcImage, srcImageLayout, dstBuffer, regionCount, pRegions)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdUpdateBuffer, vkCmdUpdateBuffer, vkCmdUpdateBuffer_fn, commandBuffer, dstBuffer, dstOffset, dataSize, pData)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdFillBuffer, vkCmdFillBuffer, vkCmdFillBuffer_fn, commandBuffer, dstBuffer, dstOffset, size, data)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPipelineBarrier, vkCmdPipelineBarrier, vkCmdPipelineBarrier_fn, commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBeginQuery, vkCmdBeginQuery, vkCmdBeginQuery_fn, commandBuffer, queryPool, query, flags)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdEndQuery, vkCmdEndQuery, vkCmdEndQuery_fn, commandBuffer, queryPool, query)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdResetQueryPool, vkCmdResetQueryPool, vkCmdResetQueryPool_fn, commandBuffer, queryPool, firstQuery, queryCount)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdWriteTimestamp, vkCmdWriteTimestamp, vkCmdWriteTimestamp_fn, commandBuffer, pipelineStage, queryPool, query)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyQueryPoolResults, vkCmdCopyQueryPoolResults, vkCmdCopyQueryPoolResults_fn, commandBuffer, queryPool, firstQuery, queryCount, dstBuffer, dstOffset, stride, flags)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdExecuteCommands, vkCmdExecuteCommands, vkCmdExecuteCommands_fn, commandBuffer, commandBufferCount, pCommandBuffers)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateEvent, vkCreateEvent, vkCreateEvent_fn, device, pCreateInfo, pAllocator, pEvent)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyEvent, vkDestroyEvent, vkDestroyEvent_fn, device, event, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetEventStatus, vkGetEventStatus, vkGetEventStatus_fn, device, event)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkSetEvent, vkSetEvent, vkSetEvent_fn, device, event)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkResetEvent, vkResetEvent, vkResetEvent_fn, device, event)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateBufferView, vkCreateBufferView, vkCreateBufferView_fn, device, pCreateInfo, pAllocator, pView)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyBufferView, vkDestroyBufferView, vkDestroyBufferView_fn, device, bufferView, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateShaderModule, vkCreateShaderModule, vkCreateShaderModule_fn, device, pCreateInfo, pAllocator, pShaderModule)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyShaderModule, vkDestroyShaderModule, vkDestroyShaderModule_fn, device, shaderModule, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreatePipelineCache, vkCreatePipelineCache, vkCreatePipelineCache_fn, device, pCreateInfo, pAllocator, pPipelineCache)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyPipelineCache, vkDestroyPipelineCache, vkDestroyPipelineCache_fn, device, pipelineCache, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPipelineCacheData, vkGetPipelineCacheData, vkGetPipelineCacheData_fn, device, pipelineCache, pDataSize, pData)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkMergePipelineCaches, vkMergePipelineCaches, vkMergePipelineCaches_fn, device, dstCache, srcCacheCount, pSrcCaches)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateComputePipelines, vkCreateComputePipelines, vkCreateComputePipelines_fn, device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyPipeline, vkDestroyPipeline, vkDestroyPipeline_fn, device, pipeline, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreatePipelineLayout, vkCreatePipelineLayout, vkCreatePipelineLayout_fn, device, pCreateInfo, pAllocator, pPipelineLayout)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyPipelineLayout, vkDestroyPipelineLayout, vkDestroyPipelineLayout_fn, device, pipelineLayout, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateSampler, vkCreateSampler, vkCreateSampler_fn, device, pCreateInfo, pAllocator, pSampler)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroySampler, vkDestroySampler, vkDestroySampler_fn, device, sampler, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateDescriptorSetLayout, vkCreateDescriptorSetLayout, vkCreateDescriptorSetLayout_fn, device, pCreateInfo, pAllocator, pSetLayout)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyDescriptorSetLayout, vkDestroyDescriptorSetLayout, vkDestroyDescriptorSetLayout_fn, device, descriptorSetLayout, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateDescriptorPool, vkCreateDescriptorPool, vkCreateDescriptorPool_fn, device, pCreateInfo, pAllocator, pDescriptorPool)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyDescriptorPool, vkDestroyDescriptorPool, vkDestroyDescriptorPool_fn, device, descriptorPool, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkResetDescriptorPool, vkResetDescriptorPool, vkResetDescriptorPool_fn, device, descriptorPool, flags)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkAllocateDescriptorSets, vkAllocateDescriptorSets, vkAllocateDescriptorSets_fn, device, pAllocateInfo, pDescriptorSets)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkFreeDescriptorSets, vkFreeDescriptorSets, vkFreeDescriptorSets_fn, device, descriptorPool, descriptorSetCount, pDescriptorSets)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkUpdateDescriptorSets, vkUpdateDescriptorSets, vkUpdateDescriptorSets_fn, device, descriptorWriteCount, pDescriptorWrites, descriptorCopyCount, pDescriptorCopies)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBindPipeline, vkCmdBindPipeline, vkCmdBindPipeline_fn, commandBuffer, pipelineBindPoint, pipeline)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBindDescriptorSets, vkCmdBindDescriptorSets, vkCmdBindDescriptorSets_fn, commandBuffer, pipelineBindPoint, layout, firstSet, descriptorSetCount, pDescriptorSets, dynamicOffsetCount, pDynamicOffsets)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdClearColorImage, vkCmdClearColorImage, vkCmdClearColorImage_fn, commandBuffer, image, imageLayout, pColor, rangeCount, pRanges)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDispatch, vkCmdDispatch, vkCmdDispatch_fn, commandBuffer, groupCountX, groupCountY, groupCountZ)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDispatchIndirect, vkCmdDispatchIndirect, vkCmdDispatchIndirect_fn, commandBuffer, buffer, offset)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetEvent, vkCmdSetEvent, vkCmdSetEvent_fn, commandBuffer, event, stageMask)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdResetEvent, vkCmdResetEvent, vkCmdResetEvent_fn, commandBuffer, event, stageMask)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdWaitEvents, vkCmdWaitEvents, vkCmdWaitEvents_fn, commandBuffer, eventCount, pEvents, srcStageMask, dstStageMask, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPushConstants, vkCmdPushConstants, vkCmdPushConstants_fn, commandBuffer, layout, stageFlags, offset, size, pValues)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateGraphicsPipelines, vkCreateGraphicsPipelines, vkCreateGraphicsPipelines_fn, device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateFramebuffer, vkCreateFramebuffer, vkCreateFramebuffer_fn, device, pCreateInfo, pAllocator, pFramebuffer)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyFramebuffer, vkDestroyFramebuffer, vkDestroyFramebuffer_fn, device, framebuffer, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateRenderPass, vkCreateRenderPass, vkCreateRenderPass_fn, device, pCreateInfo, pAllocator, pRenderPass)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyRenderPass, vkDestroyRenderPass, vkDestroyRenderPass_fn, device, renderPass, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetRenderAreaGranularity, vkGetRenderAreaGranularity, vkGetRenderAreaGranularity_fn, device, renderPass, pGranularity)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetViewport, vkCmdSetViewport, vkCmdSetViewport_fn, commandBuffer, firstViewport, viewportCount, pViewports)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetScissor, vkCmdSetScissor, vkCmdSetScissor_fn, commandBuffer, firstScissor, scissorCount, pScissors)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetLineWidth, vkCmdSetLineWidth, vkCmdSetLineWidth_fn, commandBuffer, lineWidth)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDepthBias, vkCmdSetDepthBias, vkCmdSetDepthBias_fn, commandBuffer, depthBiasConstantFactor, depthBiasClamp, depthBiasSlopeFactor)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDepthBounds, vkCmdSetDepthBounds, vkCmdSetDepthBounds_fn, commandBuffer, minDepthBounds, maxDepthBounds)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetStencilCompareMask, vkCmdSetStencilCompareMask, vkCmdSetStencilCompareMask_fn, commandBuffer, faceMask, compareMask)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetStencilWriteMask, vkCmdSetStencilWriteMask, vkCmdSetStencilWriteMask_fn, commandBuffer, faceMask, writeMask)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetStencilReference, vkCmdSetStencilReference, vkCmdSetStencilReference_fn, commandBuffer, faceMask, reference)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBindIndexBuffer, vkCmdBindIndexBuffer, vkCmdBindIndexBuffer_fn, commandBuffer, buffer, offset, indexType)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBindVertexBuffers, vkCmdBindVertexBuffers, vkCmdBindVertexBuffers_fn, commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDraw, vkCmdDraw, vkCmdDraw_fn, commandBuffer, vertexCount, instanceCount, firstVertex, firstInstance)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDrawIndexed, vkCmdDrawIndexed, vkCmdDrawIndexed_fn, commandBuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstance)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDrawIndirect, vkCmdDrawIndirect, vkCmdDrawIndirect_fn, commandBuffer, buffer, offset, drawCount, stride)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDrawIndexedIndirect, vkCmdDrawIndexedIndirect, vkCmdDrawIndexedIndirect_fn, commandBuffer, buffer, offset, drawCount, stride)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBlitImage, vkCmdBlitImage, vkCmdBlitImage_fn, commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions, filter)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdClearDepthStencilImage, vkCmdClearDepthStencilImage, vkCmdClearDepthStencilImage_fn, commandBuffer, image, imageLayout, pDepthStencil, rangeCount, pRanges)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdClearAttachments, vkCmdClearAttachments, vkCmdClearAttachments_fn, commandBuffer, attachmentCount, pAttachments, rectCount, pRects)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdResolveImage, vkCmdResolveImage, vkCmdResolveImage_fn, commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBeginRenderPass, vkCmdBeginRenderPass, vkCmdBeginRenderPass_fn, commandBuffer, pRenderPassBegin, contents)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdNextSubpass, vkCmdNextSubpass, vkCmdNextSubpass_fn, commandBuffer, contents)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdEndRenderPass, vkCmdEndRenderPass, vkCmdEndRenderPass_fn, commandBuffer)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkTrimCommandPool, vkTrimCommandPool, vkTrimCommandPool_fn, device, commandPool, flags)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroySwapchainKHR, vkDestroySwapchainKHR, vkDestroySwapchainKHR_fn, device, swapchain, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateDescriptorUpdateTemplate, vkCreateDescriptorUpdateTemplate, vkCreateDescriptorUpdateTemplate_fn, device, pCreateInfo, pAllocator, pDescriptorUpdateTemplate)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyDescriptorUpdateTemplate, vkDestroyDescriptorUpdateTemplate, vkDestroyDescriptorUpdateTemplate_fn, device, descriptorUpdateTemplate, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkUpdateDescriptorSetWithTemplate, vkUpdateDescriptorSetWithTemplate, vkUpdateDescriptorSetWithTemplate_fn, device, descriptorSet, descriptorUpdateTemplate, pData)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPushDescriptorSetWithTemplate, vkCmdPushDescriptorSetWithTemplate, vkCmdPushDescriptorSetWithTemplate_fn, commandBuffer, descriptorUpdateTemplate, layout, set, pData)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPushDescriptorSetWithTemplate2, vkCmdPushDescriptorSetWithTemplate2, vkCmdPushDescriptorSetWithTemplate2_fn, commandBuffer, pPushDescriptorSetWithTemplateInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceSparseImageFormatProperties2, vkGetPhysicalDeviceSparseImageFormatProperties2, vkGetPhysicalDeviceSparseImageFormatProperties2_fn, physicalDevice, pFormatInfo, pPropertyCount, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetImageSparseMemoryRequirements2, vkGetImageSparseMemoryRequirements2, vkGetImageSparseMemoryRequirements2_fn, device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEnumerateInstanceVersion, vkEnumerateInstanceVersion, vkEnumerateInstanceVersion_fn, pApiVersion)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkBindBufferMemory2, vkBindBufferMemory2, vkBindBufferMemory2_fn, device, bindInfoCount, pBindInfos)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkBindImageMemory2, vkBindImageMemory2, vkBindImageMemory2_fn, device, bindInfoCount, pBindInfos)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceGroupPeerMemoryFeatures, vkGetDeviceGroupPeerMemoryFeatures, vkGetDeviceGroupPeerMemoryFeatures_fn, device, heapIndex, localDeviceIndex, remoteDeviceIndex, pPeerMemoryFeatures)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDeviceMask, vkCmdSetDeviceMask, vkCmdSetDeviceMask_fn, commandBuffer, deviceMask)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkEnumeratePhysicalDeviceGroups, vkEnumeratePhysicalDeviceGroups, vkEnumeratePhysicalDeviceGroups_fn, instance, pPhysicalDeviceGroupCount, pPhysicalDeviceGroupProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetImageMemoryRequirements2, vkGetImageMemoryRequirements2, vkGetImageMemoryRequirements2_fn, device, pInfo, pMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetBufferMemoryRequirements2, vkGetBufferMemoryRequirements2, vkGetBufferMemoryRequirements2_fn, device, pInfo, pMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceFeatures2, vkGetPhysicalDeviceFeatures2, vkGetPhysicalDeviceFeatures2_fn, physicalDevice, pFeatures)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceProperties2, vkGetPhysicalDeviceProperties2, vkGetPhysicalDeviceProperties2_fn, physicalDevice, pProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceFormatProperties2, vkGetPhysicalDeviceFormatProperties2, vkGetPhysicalDeviceFormatProperties2_fn, physicalDevice, format, pFormatProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceImageFormatProperties2, vkGetPhysicalDeviceImageFormatProperties2, vkGetPhysicalDeviceImageFormatProperties2_fn, physicalDevice, pImageFormatInfo, pImageFormatProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceQueueFamilyProperties2, vkGetPhysicalDeviceQueueFamilyProperties2, vkGetPhysicalDeviceQueueFamilyProperties2_fn, physicalDevice, pQueueFamilyPropertyCount, pQueueFamilyProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceMemoryProperties2, vkGetPhysicalDeviceMemoryProperties2, vkGetPhysicalDeviceMemoryProperties2_fn, physicalDevice, pMemoryProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceQueue2, vkGetDeviceQueue2, vkGetDeviceQueue2_fn, device, pQueueInfo, pQueue)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceExternalBufferProperties, vkGetPhysicalDeviceExternalBufferProperties, vkGetPhysicalDeviceExternalBufferProperties_fn, physicalDevice, pExternalBufferInfo, pExternalBufferProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceExternalFenceProperties, vkGetPhysicalDeviceExternalFenceProperties, vkGetPhysicalDeviceExternalFenceProperties_fn, physicalDevice, pExternalFenceInfo, pExternalFenceProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceExternalSemaphoreProperties, vkGetPhysicalDeviceExternalSemaphoreProperties, vkGetPhysicalDeviceExternalSemaphoreProperties_fn, physicalDevice, pExternalSemaphoreInfo, pExternalSemaphoreProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDispatchBase, vkCmdDispatchBase, vkCmdDispatchBase_fn, commandBuffer, baseGroupX, baseGroupY, baseGroupZ, groupCountX, groupCountY, groupCountZ)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDescriptorSetLayoutSupport, vkGetDescriptorSetLayoutSupport, vkGetDescriptorSetLayoutSupport_fn, device, pCreateInfo, pSupport)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateSamplerYcbcrConversion, vkCreateSamplerYcbcrConversion, vkCreateSamplerYcbcrConversion_fn, device, pCreateInfo, pAllocator, pYcbcrConversion)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroySamplerYcbcrConversion, vkDestroySamplerYcbcrConversion, vkDestroySamplerYcbcrConversion_fn, device, ycbcrConversion, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkResetQueryPool, vkResetQueryPool, vkResetQueryPool_fn, device, queryPool, firstQuery, queryCount)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetSemaphoreCounterValue, vkGetSemaphoreCounterValue, vkGetSemaphoreCounterValue_fn, device, semaphore, pValue)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkWaitSemaphores, vkWaitSemaphores, vkWaitSemaphores_fn, device, pWaitInfo, timeout)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkSignalSemaphore, vkSignalSemaphore, vkSignalSemaphore_fn, device, pSignalInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetBufferDeviceAddress, vkGetBufferDeviceAddress, vkGetBufferDeviceAddress_fn, device, pInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetBufferOpaqueCaptureAddress, vkGetBufferOpaqueCaptureAddress, vkGetBufferOpaqueCaptureAddress_fn, device, pInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceMemoryOpaqueCaptureAddress, vkGetDeviceMemoryOpaqueCaptureAddress, vkGetDeviceMemoryOpaqueCaptureAddress_fn, device, pInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDrawIndirectCount, vkCmdDrawIndirectCount, vkCmdDrawIndirectCount_fn, commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdDrawIndexedIndirectCount, vkCmdDrawIndexedIndirectCount, vkCmdDrawIndexedIndirectCount_fn, commandBuffer, buffer, offset, countBuffer, countBufferOffset, maxDrawCount, stride)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreateRenderPass2, vkCreateRenderPass2, vkCreateRenderPass2_fn, device, pCreateInfo, pAllocator, pRenderPass)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBeginRenderPass2, vkCmdBeginRenderPass2, vkCmdBeginRenderPass2_fn, commandBuffer, pRenderPassBegin, pSubpassBeginInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdNextSubpass2, vkCmdNextSubpass2, vkCmdNextSubpass2_fn, commandBuffer, pSubpassBeginInfo, pSubpassEndInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdEndRenderPass2, vkCmdEndRenderPass2, vkCmdEndRenderPass2_fn, commandBuffer, pSubpassEndInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPhysicalDeviceToolProperties, vkGetPhysicalDeviceToolProperties, vkGetPhysicalDeviceToolProperties_fn, physicalDevice, pToolCount, pToolProperties)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCreatePrivateDataSlot, vkCreatePrivateDataSlot, vkCreatePrivateDataSlot_fn, device, pCreateInfo, pAllocator, pPrivateDataSlot)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkDestroyPrivateDataSlot, vkDestroyPrivateDataSlot, vkDestroyPrivateDataSlot_fn, device, privateDataSlot, pAllocator)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkSetPrivateData, vkSetPrivateData, vkSetPrivateData_fn, device, objectType, objectHandle, privateDataSlot, data)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetPrivateData, vkGetPrivateData, vkGetPrivateData_fn, device, objectType, objectHandle, privateDataSlot, pData)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPipelineBarrier2, vkCmdPipelineBarrier2, vkCmdPipelineBarrier2_fn, commandBuffer, pDependencyInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdWriteTimestamp2, vkCmdWriteTimestamp2, vkCmdWriteTimestamp2_fn, commandBuffer, stage, queryPool, query)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkQueueSubmit2, vkQueueSubmit2, vkQueueSubmit2_fn, queue, submitCount, pSubmits, fence)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyBuffer2, vkCmdCopyBuffer2, vkCmdCopyBuffer2_fn, commandBuffer, pCopyBufferInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyImage2, vkCmdCopyImage2, vkCmdCopyImage2_fn, commandBuffer, pCopyImageInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyBufferToImage2, vkCmdCopyBufferToImage2, vkCmdCopyBufferToImage2_fn, commandBuffer, pCopyBufferToImageInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdCopyImageToBuffer2, vkCmdCopyImageToBuffer2, vkCmdCopyImageToBuffer2_fn, commandBuffer, pCopyImageToBufferInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceBufferMemoryRequirements, vkGetDeviceBufferMemoryRequirements, vkGetDeviceBufferMemoryRequirements_fn, device, pInfo, pMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceImageMemoryRequirements, vkGetDeviceImageMemoryRequirements, vkGetDeviceImageMemoryRequirements_fn, device, pInfo, pMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceImageSparseMemoryRequirements, vkGetDeviceImageSparseMemoryRequirements, vkGetDeviceImageSparseMemoryRequirements_fn, device, pInfo, pSparseMemoryRequirementCount, pSparseMemoryRequirements)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetEvent2, vkCmdSetEvent2, vkCmdSetEvent2_fn, commandBuffer, event, pDependencyInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdResetEvent2, vkCmdResetEvent2, vkCmdResetEvent2_fn, commandBuffer, event, stageMask)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdWaitEvents2, vkCmdWaitEvents2, vkCmdWaitEvents2_fn, commandBuffer, eventCount, pEvents, pDependencyInfos)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBlitImage2, vkCmdBlitImage2, vkCmdBlitImage2_fn, commandBuffer, pBlitImageInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdResolveImage2, vkCmdResolveImage2, vkCmdResolveImage2_fn, commandBuffer, pResolveImageInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBeginRendering, vkCmdBeginRendering, vkCmdBeginRendering_fn, commandBuffer, pRenderingInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdEndRendering, vkCmdEndRendering, vkCmdEndRendering_fn, commandBuffer)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetCullMode, vkCmdSetCullMode, vkCmdSetCullMode_fn, commandBuffer, cullMode)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetFrontFace, vkCmdSetFrontFace, vkCmdSetFrontFace_fn, commandBuffer, frontFace)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetPrimitiveTopology, vkCmdSetPrimitiveTopology, vkCmdSetPrimitiveTopology_fn, commandBuffer, primitiveTopology)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetViewportWithCount, vkCmdSetViewportWithCount, vkCmdSetViewportWithCount_fn, commandBuffer, viewportCount, pViewports)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetScissorWithCount, vkCmdSetScissorWithCount, vkCmdSetScissorWithCount_fn, commandBuffer, scissorCount, pScissors)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBindVertexBuffers2, vkCmdBindVertexBuffers2, vkCmdBindVertexBuffers2_fn, commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets, pSizes, pStrides)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDepthTestEnable, vkCmdSetDepthTestEnable, vkCmdSetDepthTestEnable_fn, commandBuffer, depthTestEnable)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDepthWriteEnable, vkCmdSetDepthWriteEnable, vkCmdSetDepthWriteEnable_fn, commandBuffer, depthWriteEnable)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDepthCompareOp, vkCmdSetDepthCompareOp, vkCmdSetDepthCompareOp_fn, commandBuffer, depthCompareOp)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDepthBoundsTestEnable, vkCmdSetDepthBoundsTestEnable, vkCmdSetDepthBoundsTestEnable_fn, commandBuffer, depthBoundsTestEnable)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetStencilTestEnable, vkCmdSetStencilTestEnable, vkCmdSetStencilTestEnable_fn, commandBuffer, stencilTestEnable)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetStencilOp, vkCmdSetStencilOp, vkCmdSetStencilOp_fn, commandBuffer, faceMask, failOp, passOp, depthFailOp, compareOp)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetRasterizerDiscardEnable, vkCmdSetRasterizerDiscardEnable, vkCmdSetRasterizerDiscardEnable_fn, commandBuffer, rasterizerDiscardEnable)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetDepthBiasEnable, vkCmdSetDepthBiasEnable, vkCmdSetDepthBiasEnable_fn, commandBuffer, depthBiasEnable)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetPrimitiveRestartEnable, vkCmdSetPrimitiveRestartEnable, vkCmdSetPrimitiveRestartEnable_fn, commandBuffer, primitiveRestartEnable)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkMapMemory2, vkMapMemory2, vkMapMemory2_fn, device, pMemoryMapInfo, ppData)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkUnmapMemory2, vkUnmapMemory2, vkUnmapMemory2_fn, device, pMemoryUnmapInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetDeviceImageSubresourceLayout, vkGetDeviceImageSubresourceLayout, vkGetDeviceImageSubresourceLayout_fn, device, pInfo, pLayout)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetImageSubresourceLayout2, vkGetImageSubresourceLayout2, vkGetImageSubresourceLayout2_fn, device, image, pSubresource, pLayout)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCopyMemoryToImage, vkCopyMemoryToImage, vkCopyMemoryToImage_fn, device, pCopyMemoryToImageInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCopyImageToMemory, vkCopyImageToMemory, vkCopyImageToMemory_fn, device, pCopyImageToMemoryInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCopyImageToImage, vkCopyImageToImage, vkCopyImageToImage_fn, device, pCopyImageToImageInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkTransitionImageLayout, vkTransitionImageLayout, vkTransitionImageLayout_fn, device, transitionCount, pTransitions)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPushDescriptorSet, vkCmdPushDescriptorSet, vkCmdPushDescriptorSet_fn, commandBuffer, pipelineBindPoint, layout, set, descriptorWriteCount, pDescriptorWrites)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBindDescriptorSets2, vkCmdBindDescriptorSets2, vkCmdBindDescriptorSets2_fn, commandBuffer, pBindDescriptorSetsInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPushConstants2, vkCmdPushConstants2, vkCmdPushConstants2_fn, commandBuffer, pPushConstantsInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdPushDescriptorSet2, vkCmdPushDescriptorSet2, vkCmdPushDescriptorSet2_fn, commandBuffer, pPushDescriptorSetInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetLineStipple, vkCmdSetLineStipple, vkCmdSetLineStipple_fn, commandBuffer, lineStippleFactor, lineStipplePattern)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdBindIndexBuffer2, vkCmdBindIndexBuffer2, vkCmdBindIndexBuffer2_fn, commandBuffer, buffer, offset, size, indexType)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkGetRenderingAreaGranularity, vkGetRenderingAreaGranularity, vkGetRenderingAreaGranularity_fn, device, pRenderingAreaInfo, pGranularity)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetRenderingAttachmentLocations, vkCmdSetRenderingAttachmentLocations, vkCmdSetRenderingAttachmentLocations_fn, commandBuffer, pLocationInfo)
VULKAN_API_INFO_DEFINITION_V(ROCPROFILER_VULKAN_TABLE_ID, ROCPROFILER_VULKAN_API_ID_vkCmdSetRenderingInputAttachmentIndices, vkCmdSetRenderingInputAttachmentIndices, vkCmdSetRenderingInputAttachmentIndices_fn, commandBuffer, pInputAttachmentIndexInfo)
// clang-format on

#else
#    error "Do not compile this file directly. It is included by lib/rocprofiler-sdk/hip/hip.cpp"
#endif
